
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Entry devtty;

	private global::Gtk.Entry baudrate;

	private global::Gtk.Button start;

	private global::Gtk.Button send;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView serialin;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView serialout;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.devtty = new global::Gtk.Entry ();
		this.devtty.CanFocus = true;
		this.devtty.Name = "devtty";
		this.devtty.Text = global::Mono.Unix.Catalog.GetString ("/dev/ttyUSB0");
		this.devtty.IsEditable = true;
		this.devtty.InvisibleChar = '•';
		this.hbox2.Add (this.devtty);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.devtty]));
		w1.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.baudrate = new global::Gtk.Entry ();
		this.baudrate.CanFocus = true;
		this.baudrate.Name = "baudrate";
		this.baudrate.Text = global::Mono.Unix.Catalog.GetString ("115200");
		this.baudrate.IsEditable = true;
		this.baudrate.InvisibleChar = '•';
		this.hbox2.Add (this.baudrate);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.baudrate]));
		w2.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.start = new global::Gtk.Button ();
		this.start.CanFocus = true;
		this.start.Name = "start";
		this.start.UseUnderline = true;
		this.start.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.hbox2.Add (this.start);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.start]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.send = new global::Gtk.Button ();
		this.send.CanFocus = true;
		this.send.Name = "send";
		this.send.UseUnderline = true;
		this.send.Label = global::Mono.Unix.Catalog.GetString ("Send Bytes");
		this.hbox2.Add (this.send);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.send]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.serialin = new global::Gtk.TextView ();
		this.serialin.CanFocus = true;
		this.serialin.Name = "serialin";
		this.GtkScrolledWindow.Add (this.serialin);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
		w7.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.serialout = new global::Gtk.TextView ();
		this.serialout.CanFocus = true;
		this.serialout.Name = "serialout";
		this.GtkScrolledWindow1.Add (this.serialout);
		this.vbox1.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow1]));
		w9.Position = 2;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 578;
		this.DefaultHeight = 666;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.start.Clicked += new global::System.EventHandler (this.OnStartClicked);
		this.send.Clicked += new global::System.EventHandler (this.OnsendClicked);
	}
}
